title: St.Mary & St.John Fisher
subtitle: Roman Catholic Church
logo: "/assets/images/templogo.png"
email:
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to the Catholic Parish of St Mary & St John Fisher.
twitter_username: username
github_username: rcdentonchurch
minimal_mistakes_skin: air
search: true

# Build settings
markdown: kramdown
remote_theme: rcdentonchurch/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
# collections_dir: resources
collections:
  posts:
    output: true
  events: 
    output: true
  news:
    output: true
  masses:
    output: true


include:
  - _pages

parish:
  name             : St.Mary & St.John Fisher Church
  address          : Denton
  postcode         : POSTCODE
  email            : ""
  phonenumber      : +44 000000000
  sundaymass       :
    - label: "Vigil Mass"
      day  : "Saturday"
      time : "4PM" 
    - label: "Sunday Mass"
      day  : "Sunday"
      time : "11AM"
  
  vicar: "Fr. Joe"
  asstvicar: ""
  admininstrator: ""
 

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "St.Mary & St.John Fisher"
  avatar : "/assets/images/templogo.png"
  bio    : "Sunday Mass Timings: <br> Saturday 4 PM <br> Sunday 11 AM"
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://facebook.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
lunr:
  search_within_pages: true