publish_mode: editorial_workflow
media_folder: "/assets/uploads"
# site_url: https://rcdentonchurch.github.io
# display_url: https://rcdentonchurch.github.io
collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      # - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Categories", name: "categories", widget: "list", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - label: "Date"
        name: "date"
        widget: "datetime"
        default: "{{now}}"
        date_format: "DD/MM/YYYY" # e.g. 24.12.2021
        time_format: false
        format: "LLL"
        picker_utc: false
        required: false
  - name: "newsletter" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Newsletter" # Used in the UI, ie.: "New Post"
    folder: "_newsletters" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1", default: "Weekly Newsletter"}
      - {label: "Content", name: "body", default: "Our weekly news letter with upcoming events and announcements.", widget: "markdown"}
      - {label: "Keywords", name: "keywords", widget: "string", default: "Newsletter Announcements Events CAFOD", hint: "Enter keywords in the newsletter to help the site search show this result when searched."}
      - {label: "Categories", name: "categories", widget: "list", required: false, default: "Newsletter"}
      - {label: "Files",name: "files",widget: "file",media_library: {config: { multiple: true}}, required: true}
  - name: "events" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Events" # Used in the UI, ie.: "New Post"
    folder: "_events" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Content", name: "body", widget: "markdown"}
      - {label: "Categories", name: "categories", widget: "string", required: false}
      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"
        choose_url: true
        # default: "/uploads/chocolate-dogecoin.jpg"
        media_library:
          config:
            multiple: true
      - {label: "Files",name: "files",widget: "file",media_library: {config: { multiple: true}}, required: false}
  - name: "list" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Lists" # Used in the UI, ie.: "New Post"
    folder: "_listpages" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{fields.title}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Keywords", name: "keywords", widget: "list", required: false}
      - {label: "Page Link", name: "permalink", widget: "string", required: false}
      - label: "Page Layout"
        name : "layoutstyle"
        widget: "select"
        options: ["List View","Photo Gallery","Grid Gallery"]
        required: true
        default: "List View"
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "List Item"
        name: "listitem"
        widget: "list"
        summary: '{{fields.label}}'
        fields:
          - {label: Title, name: title, widget: string, default: "People"}
          - label: "Subtitle"
            name: "subtitle"
            widget: "string"
          - label: "Body"
            name: "body"
            widget: "markdown"
          - label: "Image"
            name: "thumbnail"
            widget: "image"
            choose_url: true
            # default: "/uploads/chocolate-dogecoin.jpg"
            media_library:
              config:
                multiple: false

        
      
  - name: "masses" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Mass" # Used in the UI, ie.: "New Post"
    folder: "_masses" # The path to the folder where the documents are stored
    sort: "title:asc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    summary: "{{ title }} - [ {{ visible }} ] "
    fields: # The fields each document in this collection have
      - {label: "Mass Collection", name: "title", widget: "string", default: "Lent Mass Timings"}
      - label: "Category"
        name: "key"
        hint: "Select SPECIAL for special timetabled masses, will be displayed differently on the site."
        widget: "select"
        options: ["REGULAR","SPECIAL"]
        default: "SPECIAL"
      - {label: "Visible", name: "visible", hint: "Only turn ON when you want to display this information on the site. There MUST NOT be another Mass Collection with the same category that is turned ON.", widget: "boolean", default: true}
      - label: "Mass"
        name: "masses"
        widget: "list"
        summary: '{{fields.label}} - {{fields.day}} - {{fields.time}}'
        fields:
          - {label: Label, name: label, widget: string, default: "Sunday Mass"}
          - label: "Day"
            name: "day"
            widget: "select"
            options: ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]
          - label: "Time"
            name: "time"
            widget: "datetime"
            default: "11:00"
            date_format: false # e.g. 24.12.2021
            time_format: "HH:mm"
            format: "LT"
            picker_utc: false
            required: true
          - label: "Date"
            name: "start"
            widget: "datetime"
            # default: "{{now}}"
            date_format: "DD/MM/YYYY" # e.g. 24.12.2021
            time_format: false
            format: "LLL"
            picker_utc: false
            required: false
          
      
# backend:
#   name: git-gateway
#   repo: rcdentonchurch/rcdentonchurch.github.io
#   branch: main
#   base_url: https://rcdenton.vercel.app
#   # auth_endpoint: /callback
#   commit_messages:
#     create: Create {{collection}} “{{slug}}”
#     update: Update {{collection}} “{{slug}}”
#     delete: Delete {{collection}} “{{slug}}”
#     uploadMedia: Upload “{{path}}”
#     deleteMedia: Delete “{{path}}”
#     openAuthoring: '{{message}}'

backend:
  name: github
  repo: rcdentonchurch/rcdentonchurch.github.io
  base_url: https://rcdenton.vercel.app
